# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# --- Zapper configuration ---
# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# Load and initialise completion system (Loaded first because of fzf-tab)
autoload -Uz compinit
compinit

# Load Plugins
plug "joshskidmore/zsh-fzf-history-search"
plug "aloxaf/fzf-tab"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zap-zsh/zap-prompt"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-history-substring-search"
plug "romkatv/powerlevel10k"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# --- Aliases ---
alias tree='tree -I ".git|node_modules"'
alias c='clear'
alias cat="bat"
alias ll="exa -lFh -g --icons"
alias lla="exa -laFh -g --icons"
alias exa='exa -laFh -g --icons'
function mkcd {
  mkdir -p "$@" && cd "$_"
}

# --- Exports ---
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:/usr/local/go/bin"
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Used for "n" to be used in the path (Node Package Manager)
export N_PREFIX="$HOME/.n"
if [[ ":$PATH:" != *":$N_PREFIX/bin:"* ]]; then
    export PATH="$N_PREFIX/bin:$PATH"  # Added by n-install (see http://git.io/n-install-repo).
fi

# Appended Backdrop to PATH, done by install script.
export PATH=$PATH:$HOME/.backdrop/bin
